version: '2'

services:
  minio:
    image: registry.drycc.cc/drycc-addons/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'

volumes:
  minio_data:
    driver: local
